on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test, Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        shell: bash
        run: ./install.sh linux
      - name: Build
        run: poetry build
      - name: Test
        run: |
          source venv/bin/activate
          pytest
      - name: Upload built packages
        uses: actions/upload-artifact@v3
        with:
          name: build-{{ matrix.python-version }}
          path: dist
